---
title: "Data cleanup"
output: html_notebook
---

The processing of raw data carried out in R prior to analysis.

Packages

```{r, message=FALSE}
library(lubridate) 
library(tidyverse) 
library(circular) 
library(readxl) 
```

ADCP data after processing in and export from proprietary packages; Velocity, Storm, WinADCP, and WavesMon


Wave data
```{r}

sentalda<-read_csv("./Data/ADCP/aldasentv.csv")

sentalda$datetime<-ISOdate(sentalda$Year,sentalda$Month,sentalda$Day,sentalda$Hour,sentalda$Min,sentalda$Sec) 
sentalda$hourly<- round_date(sentalda$datetime, "hours")
sentalda$tenmin<-floor_date(sentalda$datetime, "10 minutes") 

sent<-sentalda[,8:30]

write_csv(sent, "sentwaves.csv")

awacseinni<-read_table( "./Data/ADCP/awacaldamars.txt",
  col_names = FALSE,
  col_types = cols(
    X1 = col_double(),
    X2 = col_double(),
    X4 = col_double(),
    X6 = col_double()
   )
  ) 

awacfyrri<-read_table( "./Data/ADCP/awacaldavetur.txt",
  col_names = FALSE,
  col_types = cols(
    X1 = col_double(),
    X2 = col_double(),
    X4 = col_double(),
    X6 = col_double()
   )
  )

colnames(awacfyrri) <- c("month","day","year", "hour","minute","second","spectrumtype","Hm0","H3","H10","Hmax","Hmean","Tm02","Tp","Tz","T3","T10","Tmax","DirTp","SprTp","Mdir","unidirectind","mpressure","mASTd","mASTice","nodetects","baddetects","zerocrossings","currentspeed","currentdir","errorcode")

awacfyrri$datetime<-ISOdate(awacfyrri$year,awacfyrri$month,awacfyrri$day,awacfyrri$hour,awacfyrri$minute,awacfyrri$second) 
awacfyrri$hourly<- round_date(awacfyrri$datetime, "hours") 
awacfyrri$tenmin<-floor_date(awacfyrri$datetime, "10 minutes")

colnames(awacseinni) <- c("month","day","year", "hour","minute","second","spectrumtype","Hm0","H3","H10","Hmax","Hmean","Tm02","Tp","Tz","T3","T10","Tmax","DirTp","SprTp","Mdir","unidirectind","mpressure","mASTd","mASTice","nodetects","baddetects","zerocrossings","currentspeed","currentdir","errorcode")

awacseinni$datetime<-ISOdate(awacseinni$year,awacseinni$month,awacseinni$day,awacseinni$hour,awacseinni$minute,awacseinni$second)
awacseinni$hourly<- round_date(awacseinni$datetime, "hours") 
awacseinni$tenmin<-floor_date(awacseinni$datetime, "10 minutes") 

awac1<-awacfyrri[,8:34]
awac2<-awacseinni[,8:34]
awac2<-awac2[,-c(17:21)]
awac1<-awac1[,-c(17:21)]

awac<-rbind(awac1,awac2)
awac<-subset(awac,currentspeed<1)
awac<-subset(awac, Hm0<4)

write_csv(awac, "awacwaves.csv")

```

Current data
```{r}
sentu<-read_csv2("u.csv")
sentv<-read_csv2("v.csv")

sentu$YR<-sentu$YR+2000
sentu$datetime<-ISOdate(sentu$YR,sentu$MO,sentu$DA,sentu$HH,sentu$MM,sentu$SS)

sentv$YR<-sentv$YR+2000
sentv$datetime<-ISOdate(sentv$YR,sentv$MO,sentv$DA,sentv$HH,sentv$MM,sentv$SS)

sentu<-sentu[8:17]
sentv<-sentv[8:17]

colnames(sentu)<-c("u1","u2","u3","u4","u5","u6","u7","u8","u9","datetime")
colnames(sentv)<-c("v1","v2","v3","v4","v5","v6","v7","v8","v9","datetime")

sentu<-sentu %>% 
  group_by(datetime) %>% 
  summarise_if(is.numeric,mean)

sentv<-sentv %>% 
  group_by(datetime) %>% 
  summarise_if(is.numeric,mean)

sentu<-sentu %>% 
  mutate_at(vars(matches("u")),`/`,y=1000) 

sentv<-sentv %>% 
  mutate_at(vars(matches("v")),`/`,y=1000) 

sentu<-sentu %>% 
  rowwise %>% 
  mutate(meanu = mean(c(u1,u2,u3,u4,u5,u6,u7,u8,u9),na.rm=TRUE))
  
sentv<-sentv %>% 
  rowwise %>% 
  mutate(meanv = mean(c(v1,v2,v3,v4,v5,v6,v7,v8,v9),na.rm=TRUE)) 

sentuv<-sentu %>% 
  left_join(sentv, by=c("datetime"="datetime"))

sentuv$fivemin<-floor_date(sentuv$datetime, "5 minutes")

sentuv<-sentuv %>% 
  mutate(mag1 = sqrt(u1^2+v1^2)) %>% 
  mutate(dir1 = ((180/pi)*(atan2(u1,v1)))%%360) %>% 
  mutate(mag2 = sqrt(u2^2+v2^2)) %>% 
  mutate(dir2 = ((180/pi)*(atan2(u2,v2)))%%360) %>% 
  mutate(mag3 = sqrt(u3^2+v3^2)) %>% 
  mutate(dir3 = ((180/pi)*(atan2(u3,v3)))%%360) %>%
  mutate(mag4 = sqrt(u4^2+v4^2)) %>% 
  mutate(dir4 = ((180/pi)*(atan2(u4,v4)))%%360) %>%
  mutate(mag5 = sqrt(u5^2+v5^2)) %>% 
  mutate(dir5 = ((180/pi)*(atan2(u5,v5)))%%360) %>%
  mutate(mag6 = sqrt(u6^2+v6^2)) %>% 
  mutate(dir6 = ((180/pi)*(atan2(u6,v6)))%%360) %>%
  mutate(mag7 = sqrt(u7^2+v7^2)) %>% 
  mutate(dir7 = ((180/pi)*(atan2(u7,v7)))%%360) %>%
  mutate(mag8 = sqrt(u8^2+v8^2)) %>% 
  mutate(dir8 = ((180/pi)*(atan2(u8,v8)))%%360) %>%
  mutate(mag9 = sqrt(u9^2+v9^2)) %>% 
  mutate(dir9 = ((180/pi)*(atan2(u9,v9)))%%360)

sentuv<-sentuv %>% 
  filter(!is.na(u1)) %>% 
  rowwise %>% 
  mutate(meandir = mean(circular(c(dir1,dir2,dir3,dir4,dir5,dir6,dir7,dir8,dir9), units="degrees"),na.rm=TRUE)%%360) %>% 
  mutate(meanmag = mean(c(mag1,mag2,mag3,mag4,mag5,mag6,mag7,mag8,mag9),na.rm=TRUE))

sentfivemin<-sentuv %>% 
  group_by(fivemin) %>% 
  summarise_at(vars(contains(c("mag","v","u","speed"))),mean)

sentdir4<-sentuv %>% 
  group_by(fivemin) %>% 
  summarise(dir4=mean(circular(dir4, units="degrees"),na.rm=TRUE)%%360)

sentmeandir<-sentuv %>% 
  group_by(fivemin) %>% 
  summarise(meandir=mean(circular(meandir, units="degrees"),na.rm=TRUE)%%360)

sentfivemin<-sentfivemin %>% 
  left_join(sentdir4, by="fivemin") %>% 
  left_join(sentmeandir, by="fivemin")

write_csv(sentfivemin,"sentvfivemins.csv")

#Awac

awacstreym<-read_csv2("awacstreym.csv")
awacstreym$DateTime<-as.POSIXct(awacstreym$DateTime,format="%d.%m.%Y %H:%M")

#Gera rundaðar tíðarvariablar
awacstreym$hourly<- round_date(awacstreym$DateTime, "hours") #Runda í tímum
awacstreym$tenmin<-floor_date(awacstreym$DateTime, "10 minutes") #Runda í 10 minuttum

#Rokna miðal streymstyrki og rætning
awacstreym<-awacstreym %>% 
  rowwise() %>% 
  mutate(meandir = mean(circular(c(dir1,dir2,dir3,dir4,dir5,dir6), units="degrees"))%%360) %>% 
  mutate(meanmag = mean(mag1,mag2,mag3,mag4,mag5,mag6))

write_csv(awacstreym, "awaccurrent.csv")

```

Tidal analysis data

```{r}
nusouthanalysis<-read_csv("tidalanalysis_mean.csv")

nusouthanalysis<-nusouthanalysis[c(8:10)]

names(nusouthanalysis)[1]<-"meanu"
names(nusouthanalysis)[2]<-"meanv"

nusouthanalysis$speedmean<-sqrt(nusouthanalysis$meanu^2+nusouthanalysis$meanv^2)/1000
nusouthanalysis$dirmean<-((180/pi)*(atan2(nusouthanalysis$meanu,nusouthanalysis$meanv)))%%360

write_csv(nusouthanalysis,"nusentanalysis.csv")

```


